location = /games/flappynifty {
    return 301 /games/flappynifty/;
}

location /games/flappynifty/ {
    proxy_pass http://unix:/run/flappynifty.sock;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
}

location = /games/flappysniffy {
    return 301 /games/flappynifty/$is_args$args;
}

location /games/flappysniffy/ {
    rewrite ^/games/flappysniffy/(.*)$ /games/flappynifty/$1 permanent;
}
